### ISSUE TITLE
AWS account not belonging to an organization

### ISSUE THREAD

**Issue by 8llouch** [loopingz/ivoryshield#11]
## Expected behavior
When my account doesn't belong to an organization credentials should work and list only one account
## Actual behavior
UnhandledPromiseRejectionWarning: AWSOrganizationsNotInUseException: Your account is not a member of an organization.
## Steps to reproduce the behavior
Use credential from account that doesn't belong to an organization

**Comment by loopingz** [comment]
Solved in the 0.10.0
